---

- name: download terragrunt
  get_url:
    url: https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version.stdout }}/terragrunt_linux_386
    dest: /tmp/terragrunt
  when: "'32' in ansible_architecture and 'Linux' == ansible_system"

- name: download terragrunt
  get_url:
    url: https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version.stdout }}/terragrunt_linux_amd64
    dest: /tmp/terragrunt
  when: "'64' in ansible_architecture and 'Linux' == ansible_system"

...
