---
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - curl

- name: extract latest version number
  block:

  - name: fetch latest terragrunt version
    shell: curl -s -o /dev/null -I -w "%{redirect_url}\n" https://github.com/gruntwork-io/terragrunt/releases/latest | grep -oP "[0-9]+(\.[0-9]+)+$"
    args:
      executable: /bin/bash
    register: latest_terragrunt_version

  - name: set terragrunt_version
    set_fact:
      terragrunt_version: "{{ latest_terragrunt_version.stdout }}"

  when: terragrunt_version == "latest"

- name: Check terragrunt version
  shell: "terragrunt --version 2>&1 | grep {{ terragrunt_version }}"
  failed_when: false
  changed_when: false
  register: terragrunt_versions_match

- include: download.yml
  when: terragrunt_versions_match.rc != 0

- name: Copy terragrunt to /usr/local/bin/terragrunt
  copy:
    src: /tmp/terragrunt
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  when: terragrunt_versions_match.rc != 0

...
